class Code():
    def code(x):
        A=['alarms are active',
            'All CASSETTE FAULTED',
            'Anti Skimming',
            'ANY CASSETTE FAULTED',
            'Billetes atascados en dispensador',
            'both supply and supervisor switches on',
            'card reader failure',
            'cash handler  fatal',
            'cash handler  suspended',
            'cash handler reject bin overfill',
            'CASHOUT',
            'cassette  3  not configured',
            'cassette  4 not configured',
            'cassette 1 faulted',
            'cassette 1 low on cash',
            'CASSETTE 1 NOT PRESENT',
            'cassette 1 out of cash',
            'cassette 2 faulted',
            'cassette 2 low on cash',
            'CASSETTE 2 NOT PRESENT',
            'cassette 2 out of cash',
            'cassette 3 faulted',
            'cassette 3 low on cash',
            'CASSETTE 3 NOT PRESENT',
            'cassette 3 out of cash',
            'cassette 4 faulted',
            'cassette 4 low on cash',
            'CASSETTE 4 NOT PRESENT',
            'cassette 4 out of cash',
            'close',
            'coin dispenser not configured',
            'depository not configured',
            'Door contact sensor alarm is on',
            'down communication failure',
            'encrypted pin not configured',
            'encrypted pin pad failure',
            'Encryption Key Failure',
            'Falla Warning Card Reader Writer',
            'inactivity timeouts have occurred',
            'lead through lamp not configured',
            'magnetic card read write  fatal',
            'magnetic card read write  suspended',
            'magnetic card read write warning',
            'NO CASSETTE CONFIGURED',
            'power failure',
            'Puertas Abiertas',
            'receipt printer faulted',
            'receipt printer paper low',
            'securomatic not configured',
            'statement printer not configured',
            'supervisor mode alarm is on',
            'supervisor switch on',
            'supply switch on',
            'touch screen not configured']
        return A[x]